### ISSUE TITLE
Question about embeds

### ISSUE THREAD

**Issue by Frankity** [Hellsing/DiscordWebhook#1]
this is not an issue, is more like a question about how to use embed on send function, i mean how to implement, i have this:

```
Embed eb = new Embed();
EmbedField field = new EmbedField();
field.Name = "Ingreso";
field.Value = "aaaaaa";
eb.Author.Name = "SilentBot";
eb.Fields.Add(field);
eb.Title = "Joining";

hookSender.Send($"<= {p.Name} se marcho del servidor **{s.Hostname}**", "SilentBot", null, false, eb);
```
eb as last parameter gives me an eror

**Comment by Hellsing** [comment]
The last parameter needs to be of type `IEnumerable<Embed>` which can be solved by using `new[] { eb }` instead of plain `eb`.

**Comment by Frankity** [comment]
Oooooh ok ty very much, very useful library and implementation.
